apiVersion: apps/v1
kind: Deployment
metadata:
  name: citbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citbot
  template:
    metadata:
      labels:
        app: citbot
    spec:
      containers:
      - name: citbot
        image: "gitlab-registry.maruru.me/nsslums/cit-bot:0.1.1"
        env:
        # auth
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: duscord-token
      imagePullSecrets:
      - name: gitlab-nsslums-citbot
