apiVersion: apps/v1
kind: Deployment
metadata:
  name: citbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citbot
  template:
    metadata:
      labels:
        app: citbot
    spec:
      containers:
        - name: citbot
          image: "gitlab-registry.maruru.me/nsslums/cit-bot:2474a53b729616300019eb0c959fa7b522fdaf2c"
          env:
            # auth
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: duscord-token
            - name: DATA_DIR
              value: /mnt/data
          volumeMounts:
            - mountPath: "/mnt/data"
              name: data
      imagePullSecrets:
        - name: gitlab-nsslums-citbot
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-data
            readOnly: false
