apiVersion: v1
kind: Secret
metadata:
  name: gitlab-nsslums-citbot
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <registry connect info>

# 以下のjsonをbase64エンコードして<registry connect info>に挿入
# gitlab container registryの場合はdeploy tokenを使用
#
#{
#        "auths": {
#                "レジストリホスト名": {
#                        "auth": "「ユーザー名:アクセストークン」をbase64エンコード"
#                }
#        }
#}