name: ci

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "gitlab-registry.maruru.me/nsslums/cit-bot:${{ github.sha }}"
    # このリポジトリに対する書き込み権限を付与
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Login GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: gitlab-registry.maruru.me
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./container/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
      -
        name: chage docker image
        uses: mikefarah/yq@master
        with:
          cmd: yq '.spec.template.spec.containers[0].image = env(IMAGE)' -i ${{ env.WORK_DIR }}k8s/syncing/citbot.yaml
      -
        name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
